name: CI

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]    

jobs:
  web_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      # https://github.com/subosito/flutter-action
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.0.2'
        channel: 'stable'
    - name: "Web Build 🔧"
      run: |
        flutter pub get
        flutter build web
    - name: "Web Deploy 🚀"
      # https://github.com/JamesIves/github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        branch: gh-pages
        folder: build/web

  app_build_and_release:
    # build app and release only on tag push
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: macos-latest
    steps:
      uses: actions/checkout@v2.3.1
      uses: actions/setup-java@v1
      with:
        java-version: "12.x"
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.0.2'
        channel: "stable"
      run: flutter pub get
    - name: Build Android App
      run: flutter build apk --debug --target-platform android-arm,android-arm64 --split-per-abi
    - name: Build iOS App
      run: |
        flutter build ios --release --no-codesign
        cd build/ios/iphoneos
        mkdir Payload
        cd Payload
        ln -s ../Runner.app
        cd ..
        zip -r app.ipa Payload
    - name: Release Apps
      uses: ncipollo/release-action@v1
      with:
        # tag: ${{ env.APP_VERSION }}
        # name: ${{ env.APP_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "build/app/outputs/apk/debug/*.apk,build/ios/iphoneos/app.ipa"
